---
- hosts: testing
  become: true
  become_user: root
  tasks:
   - name: Install apache2 Package
     yum: name=apache2 state=present
   - name: Start the apache2 Services
     service: name=apache2 state=started
   - name: Deploy the web page onto Apache Webserver.
     copy: src=/opt/playbooks/hello_world.html dest=/var/www/html
     notify: restart apache2 Services
  handlers:
   - name: restart apache2 Services
     service: name=apache2 state=restarted
