---

- hosts: testing
  become: true
  become_user: root
  tasks:
    - name: Copy a file from source to destination
      copy: src=/opt/playbooks/file1.txt dest=/tmp

    - name: create an sh file
      copy:
        dest: "/tmp/test.sh"
        content:
          echo $HOSTNAME
    - name: Execute the file
      command: '"bash /tmp/test.sh" -v'
